name: Deploy IntelliMix to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /IntelliMix
            git reset --hard
            git pull origin main
            sudo systemctl restart intellimix
            sudo systemctl restart nginx
            sudo systemctl status intellimix
            sudo systemctl status nginx
